[package]
name = "keyrock"
version = "0.1.0"
authors = ["Roberto Torres <ts.roberto@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
